---
title: "Welcome To My Blog"
author: "Melinda Stueber"
date: "2026-05-07"
categories: [health]
---

Welcome to my first time blogging. Anticipate pure awesomeness without any flaws 🤌.


```{r, echo = FALSE}
library(ggplot2)
  
diseases <- data.frame(
  year = c(2020, 2020, 2024, 2025, 2026, 2026),
  diagnosis = c(
    "Hypermobility",
    "Celiac Disease",
    "Gastroparesis",
    "Non-Radiographic Axial Spondyloarthritis",
    "Orthostatic Hypotension",
    "Psoriasis"
  ),
  side = c(-1, 1, -1, 1, -1, 1)
)

ggplot(diseases, aes(x = side, y = year)) +
  geom_hline(yintercept = unique(diseases$year),
             color = "white", linewidth = 0.5) +
  geom_point(aes(x = 0, color = diagnosis), size = 5) +
  geom_segment(aes(x = 0), xend = diseases$side * 0.6) +
  geom_vline(xintercept = 0, color = "darkgray") +
    geom_label(aes(x = side * 0.75, label = diagnosis),
             size = 4, label.size = 0.7,
             label.padding = unit(0.4, "lines"),
             hjust = ifelse(diseases$side == -1, 1, 0),
             color = "#3d3d3a", fill = "white") +
  scale_y_continuous(breaks = c(2020, 2024, 2025, 2026),
                     limits = c(2018, 2027)) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  labs(title = "My Diagnosis Journey",
       x = NULL, y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(size = 14, hjust = 0.5, margin = margin(b = 12)),
    legend.position = "none"
  )
```

Above is my fun path of diagnosis. Like many people, I am sure, the first diagnosis was not the first time symptoms appeared. I started having symptoms the moment I popped out of the womb. My intestines decided early on that participating in digestion was just too much work (it probably didn't help that my food intake ranged from cheese, bread, and occasionally, too many FiberOne bars in a single setting). I recall once, when I was in middle school, my friend came over to hang out, and we got hungry, which was usually every two minutes when you are a young, growing child. I decided to eat some FiberOne bars, and I could chunk four or five of 'em without any issue. My friend decided to follow in my footsteps, and we found out quickly that perhaps not everyone had a stomach that just won't process things that fast. She went home and got very sick (whoopsies). I was also always getting sick, things moving too fast (I know crazy) or not moving enough, and I remember thinking "wow, everyone else is just so much more graceful at handling this than me." The pediatrician would just shrug his shoulders and chalk it up to a poor diet when my mother brought up my stomach problems. Now, to be fair to the man, my diet wasn't the best. I had the cravings of a starving 18th-century woman. I wanted carbs and sugar and lots of cheese. So he wasn't technically wrong, but even when my mom made me eat vegetables and salads and actual food, not microwaved nachos, my stomach was still an absolute disaster. When my legs started hurting in high school in the middle of the night, to the point of waking me up to stare at the old glow-in-the-dark stars on my ceiling and wait for it to stop, the doctors didn't really know what to do. It wasn’t until I was 25, unable to walk faster than the elderly in the grocery store (and boy did I try), that I really pushed to figure things out and ended up getting diagnosed with non-radiographic axial spondyloarthritis (if you ever want to impress anyone at a party, just whip that word out). I won’t give you too much more of my woes just yet, but I want people to know - you are not alone when you feel like your body is off and doctors can’t see anything. I also want people to know that without advocating for myself and without the doctors who listened to me (giant shout-out to them), I wouldn’t have gotten the diagnoses. And the most important thing about getting diagnosed isn’t to have friends make Pokémon characters for each one to say you’re trying “to catch them all”, but to learn how to treat them and adapt to your body instead of pushing it to work like everyone else's. 